function htmlSet = Fcn_htmlSet(filename, dataLines)
%IMPORTFILE Import data from a text file
%  HTMLENTITYBASICSET = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  HTMLENTITYBASICSET = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  htmlEntityBasicSet = importfile("C:\Users\Administrador\OneDrive - ANATEL\_MatlabProjects\Post-Processing\ReportGeneratorGUI\htmlEntityBasicSet.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 25-Jan-2021 07:47:27

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5); 

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Char", "Dec", "Hex", "Entity", "Name"];
opts.VariableTypes = ["string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Char", "Dec", "Hex", "Entity", "Name"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Char", "Dec", "Hex", "Entity", "Name"], "EmptyFieldRule", "auto");

% Import the data
htmlSet = readtable(filename, opts);

end